volumes:
  pg-data:

services:
  pgsql:
    container_name: pgsql
    image: bitnami/postgresql:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: scheduler
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  scheduler:
    image: ray2/scheduler:latest
    container_name: scheduler
    environment:
      DB_HOST: pgsql
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - pgsql