spring:
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:9001
          predicates:
            - Path=/login, /login/**, /logout, /oauth2/authorization/**
        - id: algorithm_service
          uri: http://localhost:9002
          predicates:
            - Path=/upload, /download, /resultUpload, /upload/**
        - id: classroom_service
          uri: http://localhost:9003
          predicates:
            - Path=/**