volumes:
  pg-data:
  redis-data:

services:
  nginx:
    container_name: nginx
    image: nginx:1.26-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./domain:/domain
    depends_on:
      - gateway
  pgsql:
    container_name: pgsql
    image: bitnami/postgresql:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: scheduler
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:7-alpine
    command: redis-server --requirepass ${DB_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
  scheduler:
    image: ray2/course-main:latest
    container_name: course-scheduler
    environment:
      SERVER_PORT: 9003
      DB_HOST: pgsql
      DB_PASSWORD: ${DB_PASSWORD}
      PUBLIC_KEY: ${PUBLIC_KEY}
    expose:
      - "9003"
    depends_on:
      - pgsql
      - redis
  algorithm:
    image: ray2/course-algorithm:latest
    container_name: course-algorithm
    environment:
      SERVER_PORT: 9002
      DB_HOST: pgsql
      DB_PASSWORD: ${DB_PASSWORD}
      PUBLIC_KEY: ${PUBLIC_KEY}
    expose:
      - "9002"
    depends_on:
      - pgsql
      - redis
  auth:
    image: ray2/course-auth:latest
    container_name: course-auth
    environment:
      SERVER_PORT: 9001
      DB_HOST: pgsql
    env_file:
      - .env
    expose:
      - "9001"
  gateway:
    image: ray2/course-gateway:latest
    container_name: course-gateway
    environment:
      SERVER_PORT: 9000
    ports:
      - "9000:9000"