name: Project CD with service disruption

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
      - name: Copy frontend files
        run: |
          cp -R ./frontend/dist/* ./src/main/resources/static/
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Maven Test
        run: mvn -B test --file pom.xml
      - name: Copy backend files
        run: |
          cp ./target/scheduler-0.0.1.jar ./docker/scheduler-0.0.1.jar
      - name: Stop and remove all containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/ubuntu/docker
            docker stop scheduler
            docker rm scheduler
            docker rmi scheduler
      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          source: "./docker/"
          target: "/home/ubuntu"
      - name: Docker Compose Up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/ubuntu/docker
            docker build -t scheduler:latest .
            docker run -d -p 9000:9000 scheduler:latest
            docker ps -a