name: Project CD with Docker

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Stop and rerun docker container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/ubuntu
            chmod +x deploy.sh
            sh deploy.sh