name: Upload microservice to DockerHub

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code microservice branch
        uses: actions/checkout@v4
        with:
          ref: 'microservice'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push JRE Docker image
        run: docker build --no-cache -t ray2/jdk . && docker push ray2/jdk

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1
      - name: Upload with docker
        run: docker compose build && docker compose push
