name: Project CI with Maven and npm and upload to DockerHub

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
      - name: Copy frontend files
        run: |
          cp -R ./frontend/dist/* ./src/main/resources/static/
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 #v3.8.0
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d #v6.12.0
        with:
          context: .
          push: true
          tags: ray2/scheduler:latest
          secrets: |
            "AZURE_SECRET=${{ secrets.AZURE_SECRET }}"